Partial set of changes to catch-up with SOLPS-ITER 3.0.8 functionality and ease comparison across branches: - Pointing to Eirene and B2.5 submodules with associated changes - Added/Updated setup and submission scripts and template files - Added or renamed new user domains - Modified setup files for modern IMAS environments - Improved support for KSH environment (used on the ITER CI server) - Re-organized and added new configuration files to use common settings when relevant - Changed main Makefile to also compile Carre2 as part of the standard SOLPS set - Added new analysis and data manipulation scripts - Support for linear and snowflake topologies - Removing obsolescent H descriptor formats - Usage of FORT_LC variable for filename build-up - Replaced algorithmic GOTOs with CASE constructs - Many Uinp improvements - Updated b2sxdr converter - Bug fix to triageom for annular and limiter topologies - Avoiding building of temporary arrays to avoid debugger warning messages - Code clean-up, alignment (in particular line labels for NAG compiler) and tab and end-of-line whitespace removal - Consequences of modularization in B2.5 and Eirene - Use of eirmod_solps module in Uinp - Other compilation fixes - Updated AMDS database files - Added NetCDF safeties to avoid file overwrite while read - Added file handling safeties - Added nc2text_simple and nc_reduce utility programs - Added various safeties from main SOLPS-ITER branch - Type mismatch corrections - Adaptations to MSCL/1.2.2 - Removed MPI option in Uinp - Some dos2unix type conversions - Updated to CODATA 2018 constants - Added LICENSE document - Updated documentation, analysis scripts, and manual

diff --git a/doc/solps/Makefile b/doc/solps/Makefile
--- a/doc/solps/Makefile
+++ b/doc/solps/Makefile
@@ -4,10 +4,12 @@ B25DIR=${SOLPSTOP}/modules/B2.5
 PATH+=:/usr/bin:/bin
 SVN=svn
 GIT=`which git`
-PYTHON=python
-INCLUDES=b2cdca.F b2cdci.F b2cdcn.F b2cdcr.F b2cdcv.F DIMENSIONS.F B2_5.Makefile B2_5.config.ITER.ifort64 solps-iter_git.log b2plot.commands SOLPS_versions
+LATEX ?= $(shell which_latex)
+PDFTOPS ?= $(shell which_pdftops)
+PYTHON ?= python
+INCLUDES=b2cdca.F b2cdci.F b2cdcn.F b2cdcr.F b2cdcv.F DIMENSIONS.F B2_5.Makefile B2_5.config.ITER.ifort64 B2_5.config.common.ifort64 solps-iter_git.log b2plot.commands SOLPS_versions
 BIBFILES=aps.bib aug.bib divgas.bib extern.bib general.bib main.bib mnw.bib model.bib tok.bib WebofScience.bib xpb.bib
-STYFILES=drafthead.sty fullpage.sty relsize.sty subfigure.sty
+STYFILES=fancyvrb.sty fullpage.sty groff.enc microtype.sty microtype-pdftex.def parskip.sty pdftex.def relsize.sty stdclsdv.sty subfigure.sty supertabular.sty times.sty tocbibind.sty
 FILES=D/b2ag.dat D/b2ah.dat D/b2ar.dat D/b2ai.dat D/b2mn.dat D+C+He/b2ag.dat D+C+He/b2ah.dat D+C+He/b2ar.dat D+C+He/b2ai.dat D+C+He/b2mn.dat D+C+He/b2.boundary.parameters D+C+He/b2.numerics.parameters D+C+He/b2.transport.parameters D+C+He/b2.neutrals.parameters b2.transport.inputfile b2.sources.profile b2yg.dat b2yh.dat b2yi.dat b2ym.dat b2yn.dat b2yp.dat b2yq.dat b2yr.dat b2ymb.dat b2yrp.dat MDSPLUS/b2md.dat MDSPLUS/SOLPS_MODEL.TCL.index MDSPLUS/IDENT_MODEL.TCL.index MDSPLUS/SNAPSHOT_MODEL.TCL.index MDSPLUS/TALLIES_MODEL.TCL.index MDSPLUS/TIMEDEP_MODEL.TCL.index MDSPLUS/DIAG_MODEL.TCL.index shots.python_movie compare_shots.py QSUB.shot.python_movie sql_solps.py Makefile ${BIBFILES} ${STYFILES}
 
 ifeq ($(shell [ -e Makefile.local ] && echo yes || echo no ),yes)
@@ -15,19 +17,38 @@ ifeq ($(shell [ -e Makefile.local ] && echo yes || echo no ),yes)
   FILES += Makefile.local
 endif
 
-all: solps.pdf solps.ps 
+all: solps.pdf solps.ps
 
 .PHONY: bibtex thumb update_log complete force
 
-solps.dvi: solps.tex ${INCLUDES} ${FILES} solps.ind solps.bbl
-	@echo 'Building DVI manual'
-	latex -output-format dvi solps
-	-grep 'Label(s) may have changed' solps.log && latex -output-format dvi solps
+ifeq (${LATEX}, xelatex)
+solps.xdv: solps.tex ${INCLUDES} ${FILES} solps.ind solps.bbl
+	@echo 'Building XDV manual'
+	${LATEX} -no-pdf solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} -no-pdf solps
 	touch solps.idx ; sleep 1 ; touch solps.ind ; sleep 1 ; touch $@
 	[ -e solps.pdf ] && touch solps.pdf
 
+solps.ps: solps.pdf
+	${PDFTOPS} solps.pdf solps.ps
+
+else
+solps.dvi: solps.tex ${INCLUDES} ${FILES} solps.ind solps.bbl
+	@echo 'Building DVI manual'
+	${LATEX} -output-format dvi solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} -output-format dvi solps
+	touch solps.idx ; sleep 1 ; touch solps.ind ; sleep 1 ; touch $@
+	[ -e solps.pdf ] && touch solps.pdf
+
+ifeq (${LATEX}, pdflatex)
+solps.ps: solps.pdf
+	${PDFTOPS} solps.pdf solps.ps
+else
 solps.ps: solps.dvi
 	dvips -o -ta4 solps
+endif
+
+endif
 
 solps.ind: solps.idx
 	makeindex solps
@@ -35,78 +56,83 @@ solps.ind: solps.idx
 solps.idx: solps.tex
 	@echo 'Building index'
 	[ -e solps.ind ] || touch solps.ind
-	pdflatex solps
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 	makeindex solps
-	pdflatex solps
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 	touch solps.idx ; sleep 1 ; touch solps.ind ; sleep 1 ; touch solps.pdf
 
 solps.bbl: solps.tex ${BIBFILES}
 	@echo 'Building bibliography'
-	pdflatex solps
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 	bibtex solps
-	pdflatex solps
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 	touch solps.idx ; sleep 1 ; touch solps.ind ; sleep 1 ; touch solps.pdf
 
 solps.pdf: solps.tex ${INCLUDES} ${FILES} solps.ind solps.bbl
 	@echo 'Building PDF manual'
-	pdflatex solps
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 	touch solps.idx ; sleep 1 ; touch solps.ind ; sleep 1 ; touch $@
 
 thumb: solps.pdf
 	@echo 'Building thumbnails'
 	thumbpdf solps.pdf
-	pdflatex solps.tex
-	-grep 'Label(s) may have changed' solps.log && pdflatex solps
+	${LATEX} solps.tex
+	-grep 'Label(s) may have changed' solps.log && ${LATEX} solps
 
 bibtex: solps.bbl
 
-b2cdca.F:
+b2cdca.F: ${B25DIR}/src/documentation/b2cdca.F
 	ln -sf ${B25DIR}/src/documentation/b2cdca.F .
 
-b2cdci.F: ${B25DIR}/src/documentation/b2input.xml ${B25DIR}/src/documentation/b2cdci.py
-	-cd ${B25DIR}/src/documentation; ${PYTHON} b2cdci.py || echo "! Error building b2cdci.F from b2input.xml" > ${B25DIR}/src/documentation/b2cdci.F
-	ln -sf ${B25DIR}/src/documentation/b2cdci.F .
+b2cdci.F: b2input.xml ${B25DIR}/src/documentation/b2cdci.py
+	export DO_NOT_RESOLVE_ENTITIES=1; ${PYTHON} ${B25DIR}/src/documentation/b2cdci.py || echo "! Error building b2cdci.F from b2input.xml" > b2cdci.F
 
-b2cdcn.F: ${B25DIR}/src/documentation/b2input.xml ${B25DIR}/src/documentation/b2cdcn.py
-	-cd ${B25DIR}/src/documentation; ${PYTHON} b2cdcn.py || echo "! Error building b2cdcn.F from b2input.xml" > ${B25DIR}/src/documentation/b2cdcn.F
-	ln -sf ${B25DIR}/src/documentation/b2cdcn.F .
+b2cdcn.F: b2input.xml ${B25DIR}/src/documentation/b2cdcn.py
+	export DO_NOT_RESOLVE_ENTITIES=1; ${PYTHON} ${B25DIR}/src/documentation/b2cdcn.py || echo "! Error building b2cdcn.F from b2input.xml" > b2cdcn.F
 
-b2cdcr.F:
+b2cdcr.F: ${B25DIR}/src/documentation/b2cdcr.F
 	ln -sf ${B25DIR}/src/documentation/b2cdcr.F .
 
-b2cdcv.F:
+b2cdcv.F: ${B25DIR}/src/documentation/b2cdcv.F
 	ln -sf ${B25DIR}/src/documentation/b2cdcv.F .
+
+b2input.xml: ${B25DIR}/src/documentation/b2input.xml
+	ln -sf ${B25DIR}/src/documentation/b2input.xml .
 
 b2plot.commands: ${B25DIR}/src/b2plot/b2plot.F
 	-[ -e b2plot.commands ] && rm b2plot.commands || echo > /dev/null
-	sed 's:^     [^ ]:@@@:' ${B25DIR}/src/b2plot/b2plot.F | awk 'BEGIN{save=""}/^[^@][^@][^@]/&&save!=""{print save}/^[^@][^@][^@]/{save=$$0}/^@@@/{save=save" "$$0}END{print save}' | sed 's; *@@@ *;;g' | egrep "case *\( *'|description *=" | sed -e "s;.*case *('\(.*\)');cmd: \1;" -e "s; *description *= *'\(.*\)';desc: \1;" -e "s;' //';;" | awk -F: 'BEGIN{save=""}/^cmd/&&save!=""{print save}/^cmd:/{save=$$2}/^desc/{save=save"\t "$$2}END{print save}' | sed 's:\! ::' | sed "s:',':,:g" | sed "s:'':':g" | expand > b2plot.commands
+	sed 's:^     [^ ]:@@@:' ${B25DIR}/src/b2plot/b2plot.F | awk 'BEGIN{save=""}/^[^@][^@][^@]/&&save!=""{print save}/^[^@][^@][^@]/{save=$$0}/^@@@/{save=save" "$$0}END{print save}' | sed 's; *@@@ *;;g' | grep -v "IGNORE" | egrep "case *\( *'|description *=" | sed -e "s;.*case *('\(.*\)');cmd: \1;" -e "s; *description *= *'\(.*\)';desc: \1;" -e "s;' //';;" -e "s;'//';;" | awk -F: 'BEGIN{save=""}/^cmd/&&save!=""{print save}/^cmd:/{save=$$2}/^desc/{save=save"\t "$$2}END{print save}' | sed 's:\! ::' | sed "s:',':,:g" | sed "s:'':':g" | expand > b2plot.commands
 
-DIMENSIONS.F:
+DIMENSIONS.F: ${B25DIR}/src/include/DIMENSIONS.F
 	ln -sf ${B25DIR}/src/include/DIMENSIONS.F .
 
-B2_5.Makefile:
+B2_5.Makefile: ${B25DIR}/Makefile
 	ln -sf ${B25DIR}/Makefile B2_5.Makefile
 
-B2_5.config.ITER.ifort64:
+B2_5.config.ITER.ifort64: ${B25DIR}/config/config.ITER.ifort64
 	ln -sf ${B25DIR}/config/config.ITER.ifort64 B2_5.config.ITER.ifort64
+
+B2_5.config.common.ifort64: ${B25DIR}/config/config.common.ifort64
+	ln -sf ${B25DIR}/config/config.common.ifort64 B2_5.config.common.ifort64
 
 SOLPS_versions: force
 	@( cd ${SOLPSTOP} ; git describe --always | awk '{print "SOLPS-ITER version : ",$$1}' ) > SOLPS_versions_new
 	@( cd ${SOLPSTOP}/modules/B2.5 ; git describe --always | awk '{print "B2.5 version : ",$$1}') >> SOLPS_versions_new
 	@( cd ${SOLPSTOP}/modules/Eirene ; git describe --always | awk '{print "Eirene version : ",$$1}' ) >> SOLPS_versions_new
 	@( cd ${SOLPSTOP}/modules/Carre ; git describe --always | awk '{print "Carre version : ",$$1}' ) >> SOLPS_versions_new
+	@( cd ${SOLPSTOP}/modules/Carre2 ; git describe --always | awk '{print "Carre version : ",$$1}' ) >> SOLPS_versions_new
 	@( cd ${SOLPSTOP}/modules/DivGeo ; git describe --always | awk '{print "DivGeo version : ",$$1}' ) >> SOLPS_versions_new
 	@if cmp -s SOLPS_versions_new SOLPS_versions ; then rm SOLPS_versions_new ; else mv SOLPS_versions_new SOLPS_versions ; fi
 
-solps-iter_git.log: 
+solps-iter_git.log:
 	( cd ${SOLPSTOP} ; ${GIT} log --oneline ) > solps-iter_git.log
 
-update_log: 
+update_log:
 	( cd ${SOLPSTOP} ; ${GIT} log --oneline ) > solps-iter_git.log
 
 update: ${INCLUDES}
@@ -120,8 +146,8 @@ complete:
 	${MAKE} solps.ps
 	${MAKE} solps.pdf
 
-clean: 
-	rm -f solps.pdf solps.ps solps.dvi solps.aux solps.ilg solps.ind solps.idx solps.lof solps.log solps.lot solps.out solps.toc b2cdca.F b2cdci.F b2cdcn.F b2cdcr.F b2cdcv.F solps_data_git.log solps-iter_git.log B2_5.config.ITER.ifort64 B2_5.Makefile DIMENSIONS.F SOLPS_versions solps.bbl solps.blg solps.brf solps.tpt
+clean:
+	rm -f solps.pdf solps.ps solps.dvi solps.xdv solps.aux solps.ilg solps.ind solps.idx solps.lof solps.log solps.lot solps.out solps.toc b2input.xml b2cdca.F b2cdci.F b2cdcn.F b2cdcr.F b2cdcv.F solps_data_git.log solps-iter_git.log B2_5.config.ITER.ifort64 B2_5.Makefile DIMENSIONS.F SOLPS_versions solps.bbl solps.blg solps.brf solps.tpt
 
 ### WORK
 COMPARE_10814_TESEPM=/scratch/dpc/solps5.0_HD+C+He/src/Braams/b2/runs/D+C+He/2MW/compare_10814_tesepm.ps
@@ -149,3 +175,7 @@ compare_10814_tesepm_%.pdf: compare_10814_tesepm_%.ps
 	epstopdf $<
 
 compare_10814_tesepm: compare_10814_tesepm_1.pdf compare_10814_tesepm_2.pdf compare_10814_tesepm_3.pdf compare_10814_tesepm_4.pdf compare_10814_tesepm_5.pdf compare_10814_tesepm_6.pdf compare_10814_tesepm_7.pdf compare_10814_tesepm_8.pdf compare_10814_tesepm_9.pdf
+
+echo:
+	@echo LATEX=${LATEX}
+	@echo GIT=${GIT}
