Making the new post-processing scripts backward compatible + updated documentation

diff --git a/scripts/2d b/scripts/2d
--- a/scripts/2d
+++ b/scripts/2d
@@ -46,7 +46,7 @@ cp /dev/null ${tmpdir}gnuplot.data.tmp
 if ($no_nc2text == 1) then
   if ("$x" =~ *[0-9]) then
       # Multi-species quantities, called as $x = $name$is (e.g. $x = 'nasepm1')
-      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented for $no_nc2text == 1."
+      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
       exit 1
   else
       # Time, called as $x = 'timesa', or single species quantities, called as $x = $name (e.g. $x = 'nesepm')
@@ -78,32 +78,32 @@ set neutral_species_names = ()
 foreach name ($species_names)
   set last_char = `echo "$name" | awk '{print substr($0,length($0),1)}'`
   set second_last_char = `echo "$name" | awk '{print substr($0,length($0)-1,1)}'`
-    if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
-        set neutral_species_names = ($neutral_species_names $name)
-    endif
+  if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
+    set neutral_species_names = ($neutral_species_names $name)
+  endif
 end
 
 start:
   if ($no_nc2text == 1) then
     if ("$1" =~ *[0-9]) then
-        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-        echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented for $no_nc2text == 1."
-        exit 1
+      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
+      exit 1
     else
-        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-        ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
-        sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
+      # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+      ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
+      sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
     endif
   else
     if ("$1" =~ *[0-9]) then
-        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
-        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
-        @ is_plus_1 = $is + 1
-        echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
+      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+      set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
+      set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
+      @ is_plus_1 = $is + 1
+      echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
     else
-        # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-        echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
+      # Time, called as $1 = 'timesa', or single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+      echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
     endif
   endif
   shift
@@ -114,18 +114,18 @@ set args_plot=""
 set field_names = ( $args )
 foreach i ($field_names)
   if ("$i" =~ *[0-9]) then
-      # Multi-species quantities, called as $i = $name$is (e.g. $i = 'nasepm1')
-      set is = `echo "$i" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
-      set name = `echo "$i" | sed -E 's/([0-9]+)$//'`
-      @ is_plus_1 = $is + 1
-      if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
-        setenv species_name $neutral_species_names[$is_plus_1]
-      else
-        setenv species_name $species_names[$is_plus_1]
-      endif
-      set args_plot="$args_plot $name($species_name)"
+    # Multi-species quantities, called as $i = $name$is (e.g. $i = 'nasepm1')
+    set is = `echo "$i" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
+    set name = `echo "$i" | sed -E 's/([0-9]+)$//'`
+    @ is_plus_1 = $is + 1
+    if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
+      setenv species_name $neutral_species_names[$is_plus_1]
+    else
+      setenv species_name $species_names[$is_plus_1]
+    endif
+    set args_plot="$args_plot $name($species_name)"
   else
-      set args_plot="$args_plot $i"
+    set args_plot="$args_plot $i"
   endif
 end
 
