- Pointer to B2.5 submodule with bug fixes for distance along targets in analysis plots and IMAS DD/4.1.1 support - Rebuilt COMPASS example with updated analysis plots - Corrected 2d plotting scripts for JSON format Eirene input file and added safeties - Modified update scripts to point to Eirene MsV SOLPS_master branch - Updated documentation about GitHub distribution - Added test of CMake version (becomes needed with CMake version: reported by Stefano Carli) - Corrected ITER nag_90 pragmas

diff --git a/scripts/2dt b/scripts/2dt
--- a/scripts/2dt
+++ b/scripts/2dt
@@ -16,8 +16,8 @@ else
 endif
 
 if ( $#argv < 1 ) then
-    echo "Error: You must provide at least one argument (1st, 2nd, etc. arguments will be plotted vs. time)."
-    exit 1
+  echo "Error: You must provide at least one argument (1st, 2nd, etc. arguments will be plotted vs. time)."
+  exit 1
 endif
 
 set source=b2mn.exe.dir/b2time.nc
@@ -27,9 +27,9 @@ set args=""
 set nargs=0
 
 if($?GNUPLOT_TMP) then
-    set tmpdir="$GNUPLOT_TMP/"
+  set tmpdir="$GNUPLOT_TMP/"
 else
-    set tmpdir=""
+  set tmpdir=""
 endif
 
 which nc2text > /dev/null && set no_nc2text=0 || set no_nc2text=1
@@ -65,9 +65,9 @@ set neutral_species_names = ()
 foreach name ($species_names)
   set last_char = `echo "$name" | awk '{print substr($0,length($0),1)}'`
   set second_last_char = `echo "$name" | awk '{print substr($0,length($0)-1,1)}'`
-    if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
-        set neutral_species_names = ($neutral_species_names $name)
-    endif
+  if ("$last_char" == "0" && "$second_last_char" !~ [0-9]) then
+    set neutral_species_names = ($neutral_species_names $name)
+  endif
 end
 
 start:
@@ -76,28 +76,28 @@ start:
   # Works for two, did not have any cases to confirm this works for more.
   # Could break if there are enough columns that it extends across multiple lines.
     if ("$1" =~ *[0-9]) then
-        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-        echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
-        exit 1
+      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+      echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
+      exit 1
     else
-        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-        set check=`ncdump $source -v $1 | sed -n 'x;$p' | sed 's/;//g'`
+      # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+      set check=`ncdump $source -v $1 | sed -n 'x;$p' | sed 's/;//g'`
     endif
   else
     if ("$1" =~ *[0-9]) then
-        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
-        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
-        @ is_plus_1 = $is + 1
-        set check=`nc2text -n 999999 $source "$name(1,$is_plus_1)"`
-        # There is currently a bug when calling nc2text -n 999999 $source "$name(1,$is_plus_1)"
-        # for multi-species quantities: all time values are printed instead of only the first one
-        # Probably a mistake while adding additional dimensions to nc2text
-        # Temporary fix:
-        set check = ( $check[1] )
+      # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+      set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
+      set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
+      @ is_plus_1 = $is + 1
+      set check=`nc2text -n 999999 $source "$name(1,$is_plus_1)"`
+      # There is currently a bug when calling nc2text -n 999999 $source "$name(1,$is_plus_1)"
+      # for multi-species quantities: all time values are printed instead of only the first one
+      # Probably a mistake while adding additional dimensions to nc2text
+      # Temporary fix:
+      set check = ( $check[1] )
     else
-        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-        set check=`nc2text -n 999999 $source "$1(1)"`
+      # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+      set check=`nc2text -n 999999 $source "$1(1)"`
     endif
   endif
   @ nargs += $#check
@@ -105,32 +105,32 @@ start:
     if ($no_nc2text == 1) then
     # Same as timesa except we pass the variable name as string
       if ("$1" =~ *[0-9]) then
-          # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-          echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
-          exit 1
+        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+        echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
+        exit 1
       else
-          # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-          ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
-          sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
-          set args="$args $1"
+        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+        ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}  END {print "\n";}' | \
+        sed 's/,/ /g' | sed 's/;//g' >> ${tmpdir}gnuplot.data.tmp
+        set args="$args $1"
       endif
     else
       if ("$1" =~ *[0-9]) then
-          # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-          set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
-          set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
-          @ is_plus_1 = $is + 1
-          echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
-          if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
-            setenv species_name $neutral_species_names[$is_plus_1]
-          else
-            setenv species_name $species_names[$is_plus_1]
-          endif
-          set args="$args $name($species_name)"
+        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
+        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
+        @ is_plus_1 = $is + 1
+        echo `nc2text -n 9999999 $source "$name(:,$is_plus_1)"` >> ${tmpdir}gnuplot.data.tmp
+        if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
+          setenv species_name $neutral_species_names[$is_plus_1]
+        else
+          setenv species_name $species_names[$is_plus_1]
+        endif
+        set args="$args $name($species_name)"
       else
-          # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-          echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
-          set args="$args $1"
+        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+        echo `nc2text -n 9999999 $source $1` >> ${tmpdir}gnuplot.data.tmp
+        set args="$args $1"
       endif
     endif
   else
@@ -138,33 +138,33 @@ start:
     # If the data has more than one column we dump as before,
     # then assemble data into columns to be processed by awk.transpose
       if ("$1" =~ *[0-9]) then
-          # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-          echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
-          exit 1
+        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+        echo "Error: Plotting multi-species arrays from b2time.nc not yet implemented without nc2text."
+        exit 1
       else
-          # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-          ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
-          awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' | \
-          awk.transpose >> ${tmpdir}gnuplot.data.tmp
-          set args="$args `count -p $1 1 $#check`"
+        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+        ncdump $source -f f -v $1 | awk -v string="$1" 'BEGIN {ORS="";} /data:/{found1=1;next;} $0 ~ string {if (found1==1) {if (found2==1) print $1; else {print $3;found2=1;}}}' | \
+        awk 'BEGIN {FS=","} {for (i=1;i<=NF;i++) if (i%2==1) {ORS=" ";print $i;}}' | sed 's/;//g' | \
+        awk.transpose >> ${tmpdir}gnuplot.data.tmp
+        set args="$args `count -p $1 1 $#check`"
       endif
     else
       if ("$1" =~ *[0-9]) then
-          # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
-          set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
-          set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
-          @ is_plus_1 = $is + 1
-          nc2text -n 9999999 $source "$name(:,$is_plus_1)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
-          if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
-            setenv species_name $neutral_species_names[$is_plus_1]
-          else
-            setenv species_name $species_names[$is_plus_1]
-          endif
-          set args="$args `count -p $name($species_name) 1 $#check`"
+        # Multi-species quantities, called as $1 = $name$is (e.g. $1 = 'nasepm1')
+        set is = `echo "$1" | sed -E 's/.*[^0-9]([0-9]+)$/\1/'`
+        set name = `echo "$1" | sed -E 's/([0-9]+)$//'`
+        @ is_plus_1 = $is + 1
+        nc2text -n 9999999 $source "$name(:,$is_plus_1)" | awk.transpose >> ${tmpdir}gnuplot.data.tmp
+        if ("$name" =~ dab* || "$name" =~ dmb* || "$name" =~ tab* || "$name" =~ tmb*) then
+          setenv species_name $neutral_species_names[$is_plus_1]
+        else
+          setenv species_name $species_names[$is_plus_1]
+        endif
+        set args="$args `count -p $name($species_name) 1 $#check`"
       else
-          # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
-          nc2text -n 9999999 $source $1 | awk.transpose >> ${tmpdir}gnuplot.data.tmp
-          set args="$args `count -p $1 1 $#check`"
+        # Single species quantities, called as $1 = $name (e.g. $1 = 'nesepm')
+        nc2text -n 9999999 $source $1 | awk.transpose >> ${tmpdir}gnuplot.data.tmp
+        set args="$args `count -p $1 1 $#check`"
       endif
     endif
   endif
