WIP: Catching up with 3.0.8 master version - Pointing to 3.0.8 master version for Carre, DivGeo, Eirene, ADAS and AMDS - Pointing to updated B2.5 submodule (WIP/release-3.1.0, part 1) - Support for compilation environments with split configuration files between common and hostname-specific files - Added support for NAG and Cray compilers - Updated submission scripts, including chain submission capability - Added IMAS support - Added OpenMP compilation targets - Improved file handling - Usage of Eirene architecture-dependent filenames - Added new Eirene quantities in Uinp, improved support for Nitrogen reactions, added Helium CX reactions and ADAS ionization rates - Use of b2mod_subsys and eirmod_solps in Uinp - Added nc_reduce and nc2text_simple utilities - Updated to NetCDF4 usage - Added CCFE-CSD3, CUMULUS, NERSC, JFRS, USTC and MARCONI configuration files and removed IPPITM configuration files - Use of case constructs instead of deprecated algorithmic GOTOs, avoiding type mismatches - Corrected and updated documentation, added MDSPLUS tree description files - DOS to Unix conversion for some files - Updated scripts - Various minor bug fixes

diff --git a/scripts/carre b/scripts/carre
--- a/scripts/carre
+++ b/scripts/carre
@@ -28,13 +28,20 @@ The script prints the output filename after successful grid conversion to B2 for
 The directories for the input files and for the grids can be specified in the
 environmental variables CARRE_INPUTDIR and CARRE_GRIDDIR (default is the current directory).
 If the variable CARRE_STOREDIR is set, then all the input data (i.e., the control file, the
-equilibrium file, and the structures file) are saved in a directory 
+equilibrium file, and the structures file) are saved in a directory
 \$CARRE_STOREDIR/\$DEVICE/<grid number>. If this directory does not exist, it is created.
 
 Error messages and tracing data from carre (\"Grid\") and traduit (\"Convert\") can be found in
 the files carre.log and traduit.log, respectively.
 "
 [ -z "$1" ] && { /bin/echo -e "$Usage"; exit 4; }
+
+SOLPSTOP=`determine_SOLPSTOP`
+[ "$SOLPS_DEBUG" = '' ] || {
+  export EXT_DEBUG=".debug"
+}
+CARRE_PATH=$SOLPSTOP/modules/Carre/builds/$HOST_NAME.$COMPILER$EXT_DEBUG
+/bin/echo -e "CARRE_PATH : $CARRE_PATH"
 
 [ "$DEVICE" = '' ] && {
   print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
@@ -60,10 +67,17 @@ endings="dgo equ str trg"
 /bin/echo -e "Input directory: $indir\n"
 
 [ "$1" = '-' ] && {
-    /bin/echo -e "Standard linking - the input files are assumed to exist in \"$indir\""
-    q=p
-    qqs=c
-    grid_stem=`ls -ls $indir/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
+    [ -r $indir/dg.str ] && {
+      /bin/echo -e "Standard linking - the input files are assumed to exist in \"$indir\""
+      q=p
+      qqs=c
+      grid_stem=`ls -ls $indir/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
+    } || {
+      /bin/echo -e "Linking error - the input files were not found in \"$indir\""
+      /bin/echo -e "Use (I)nput command to provide correct input directory"
+      q=i
+      qqs=c
+    }
 } || { \
     u="$indir/$1"
     [ -r $u.vrq ] && [ -r $u.str ] && [ -r $u.fld ] & { \
@@ -104,7 +118,7 @@ do {
                 The stored input data (if any) for the specified grids are also removed.
   Input   (i)   specify a new directory for the input files (input directory).
                 If the specified directory does not exist and the CARRE_STOREDIR is set,
-                then the input directory is looked for in \$CARRE_STOREDIR/\$DEVICE 
+                then the input directory is looked for in \$CARRE_STOREDIR/\$DEVICE
                 and \$CARRE_STOREDIR
   Output  (o)   specify a new storage directory for the grids
   Quit    (q)   quit $script
@@ -129,17 +143,17 @@ do {
               [ -r $class.aux ] && ln -sf $class.aux dg.aux
             }
             rm -f selptx.inf carre.dat structure.dat rzpsi.dat btor.dat 2>/dev/null
-            fcrr.exe; q=g; break;;
+            $CARRE_PATH/fcrr.exe; q=g; break;;
     ( g|G )                                               # create the grid:
 #            carre.exe; q=s; break;;
-            carre.exe 2>carre.log; q=$qqs; break;;
+            $CARRE_PATH/carre.exe 2>carre.log; q=$qqs; break;;
     ( s|S )                                               # save the control data:
             cp carre.out carre.dat;
             /bin/echo -e "Saved grid settings in carre.dat file"
             q=c; break;;
     ( c|C )                                               # convert:
-            /bin/echo -e "carre.out\n4" | traduit.exe 2>traduit.log; mv traduit.out traduit.sno ;
-            /bin/echo -e "carre.out\n2" | traduit.exe 2>traduit.log; 
+            /bin/echo -e "carre.out\n4" | $CARRE_PATH/traduit.exe 2>traduit.log; mv traduit.out traduit.sno ;
+            /bin/echo -e "carre.out\n2" | $CARRE_PATH/traduit.exe 2>traduit.log;
             q=t; break;;
     ( t|T )                                               # store the grid:
             [ -r traduit.out ] && {
@@ -174,25 +188,29 @@ do {
                 touch CARRE.HISTORY
 		echo $user `date +%Y-%m-%d_%H:%M:%S` >> CARRE.HISTORY
 		ls -ls dg.??? | cut -d ' ' -f 9- >> CARRE.HISTORY
-                mv -f traduit.sno $dgdir/$grid_stem.v$m.sno && \
-                  /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno"
+                cp traduit.sno $dgdir/$grid_stem.v$m.sno && \
+                  /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" && \
+                  /bin/echo -e "The grid in DG format is stored as $dgdir/$grid_stem.v$m.sno" >> CARRE.HISTORY
+                mv -f traduit.sno $grid_stem.v$m.sno
                 for ext in $endings; do
                   filename=`lln dg.$ext`
                   cp $filename $dgdir/`basename $filename`
-                  /bin/echo -e "dg.$ext copied to $dgdir" && \
-                  /bin/echo -e "dg.$ext copied to $dgdir" >> CARRE.HISTORY
+                  /bin/echo -e "`basename $filename` copied to $dgdir" && \
+                  /bin/echo -e "`basename $filename` copied to $dgdir" >> CARRE.HISTORY
                 done
                 modelname=`echo $filename | sed -e 's\trg\dg\' `
                 cp $modelname $dgdir/`basename $modelname`
                 /bin/echo -e "DG model `basename $modelname` copied to $dgdir" && \
                 /bin/echo -e "DG model `basename $modelname` copied to $dgdir" >> CARRE.HISTORY
-                mv -f traduit.out $griddir/$grid_stem.v$m.geo && \
-                  /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo"
+                cp traduit.out $griddir/$grid_stem.v$m.geo && \
+                  /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" && \
+                  /bin/echo -e "The grid in B2.5 format is stored as $griddir/$grid_stem.v$m.geo" >> CARRE.HISTORY
+                mv -f traduit.out $grid_stem.v$m.geo
                 [ -x ctrans ] && {
                   ctrans -d ps.mono gmeta > $griddir/$grid_stem.v$m.ps && \
-                  /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps"
+                  /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" && \
+                  /bin/echo -e "You can view the grid in PostScript format as $griddir/$grid_stem.v$m.ps" >> CARRE.HISTORY
                 }
-		            /bin/echo -e "The grid is stored as $griddir/$grid_stem.v$m".geo >> CARRE.HISTORY
                 [ -n "$stordir" ] && {
                   [ -d "$stordir" ] || {
                     [ -a "$stordir" ] && {
@@ -231,7 +249,7 @@ do {
             break;;
     ( n|N )                                               # next job:
             /bin/echo -e "Input the new stem: \c"; read u
-            [ -n "$u" ] && { 
+            [ -n "$u" ] && {
               [ "$u" = '-' ] && {
                 [ -r $indir/rzpsi.dat ] && [ -r $indir/structure.dat ] && [ -r $indir/btor.dat ] && {
                   ln -sf $indir/rzpsi.dat $indir/structure.dat $indir/btor.dat . && q=g
@@ -267,9 +285,13 @@ do {
                 vv=
                 ww=
                 for n in $u; do
-                  uu="$uu $griddir/$grid_stem.v$n.geo"
-                  vv="$vv $griddir/$grid_stem.v$n.ps"
-                  ww="$ww $dgdir/$grid_stem.v$n.sno"
+                  m=$n
+                  [ ${#m} -lt 2 ] && m=00$m || {
+                    [ ${#m} -lt 3 ] && m=0$m
+                  }
+                  uu="$uu $griddir/$grid_stem.v$m.geo"
+                  vv="$vv $griddir/$grid_stem.v$m.ps"
+                  ww="$ww $dgdir/$grid_stem.v$m.sno"
                 done
                 ls -l $uu $vv $ww
                 /bin/echo -e "Do you wish to remove this grid(s)? (y/n): \c"; read u
@@ -291,7 +313,7 @@ do {
                 indir="$u"
               } || {
                 [ -n "$stordir" ] && {
-                  indir="$stordir/$u" 
+                  indir="$stordir/$u"
                   [ -d "$indir" ] || {
                     indir="$CARRE_STOREDIR/$u"
                     [ -d "$indir" ] || indir=
@@ -300,15 +322,22 @@ do {
               }
               [ -n "$indir" ] && {
                 /bin/echo -e "The input directory is now `(cd $indir && pwd)`"; q=n; true
+                [ -r $u/dg.str ] && {
+                  grid_stem=`ls -ls $u/dg.str | awk '{print $NF}' | xargs basename | sed 's:\.str$::'`
+                  q=p
+                } || {
+                  /bin/echo -e "Cannot find dg.str file in $u"
+                  q=i
+                }
               } || {
                 /bin/echo -e "Cannot find directory: $u"; q=i
               }
             }; break;;
     ( o|O )                                               # output directory:
-            /bin/echo -e "Specify the new grid directory: \c"; read u
+            /bin/echo -e "Specify the new grid storage directory: \c"; read u
             [ -n "$u" ] && {
               [ -d $u ] && {
-                griddir="$u"; /bin/echo -e "The grid directory is now $griddir"; q=t
+                griddir="$u"; /bin/echo -e "The grid storage directory is now $griddir"; q=t
               } || {
                 /bin/echo -e "No such directory: $u\nCreate it? (y/n) \c"; read uu
                 case "$uu" in
@@ -328,10 +357,10 @@ do {
                           /bin/echo -e "Creating $ss"
                           mkdir -p $ss && {
                             griddir="$u"; q=t
-                            /bin/echo -e "The grid directory is now $griddir"
+                            /bin/echo -e "The grid storage directory is now $griddir"
                           } || {
                             /bin/echo -e "Unable to create $u"; q=o
-                            /bin/echo -e "The grid directory is still $griddir"
+                            /bin/echo -e "The grid storage directory is still $griddir"
                           };;
                   (  *  ) ;;
                 esac
