Continued preparatory steps for multi-threaded compilation: - Added a prereqs set of targets - Separated libeirene.a and libeirene_nox.a targets - Removed target duplications - Better management of NetCDF targets - Updated OpenMP environment scripts - Corrected module names for setup.ksh.ITER.gfortran (provided by Simon Pinches) - Updated documentation - Pointer to B2.5 submodule with safety when .new_module is updated, improved handling of complex variables, and corrected b2stbc_phys output (reported by Egbert Westerhof) - Pointer to Carre submodule with better b2mod_dimensions handling - Pointer to DivGeo submodule with safeties for multi-threaded compilation - Pointer to Eirene submodule with better handling of complex variables and Makefile safeties - Added safeties when building LISTOBJ and dependencies files during multi-threaded compilation - Added some explicit dependencies for b2sxdr compilation - Rebuilt CI test cases with corrected RCX.. output - Make sure the debug CI test case is building from a clean state - Added early build fail diagnostics in batch compilation scripts

diff --git a/scripts/efgwmake b/scripts/efgwmake
--- a/scripts/efgwmake
+++ b/scripts/efgwmake
@@ -123,15 +123,16 @@ sed \
   -e 's:#COMPILER#:'$COMPILER':g' \
   < $QSUB > $NAME
 
+echo "set build_failed = 0" >> $NAME
 if ("X${options}X" != "XX") then
-  echo "${MAKE} MAKE_OPTIONS='${options}' ${objects} >>& make.log.${COMPILER}" >> $NAME
+  echo "${MAKE} MAKE_OPTIONS='${options}' ${objects} >>& make.log.${COMPILER} || set build_failed = 1" >> $NAME
 else
-  echo "${MAKE} ${objects} >>& make.log.${COMPILER}" >> $NAME
+  echo "${MAKE} ${objects} >>& make.log.${COMPILER} || set build_failed = 1" >> $NAME
 endif
+echo 'exit $build_failed' >> $NAME
 
 if ($chain == "unset") then
   sbatch $NAME
 else
   sbatch --dependency=afterany:${chain} $NAME
 endif
-
