- Corrected SOLPS4-5 converter for cases with simultaneous density feedback core and SOL control (required to translate case #2360 as part of task IMAS-1246) - Fixes for optional file handling - Module corrections for pgf90 ITER environment - Pointing to B2.5 and Eirene submodules with memory leak and debugging fixes

diff --git a/scripts/move_optional_files b/scripts/move_optional_files
--- a/scripts/move_optional_files
+++ b/scripts/move_optional_files
@@ -2,48 +2,71 @@
 
 NAME=/tmp/.files.$$.$USER.`date +%Y%m%d%H%M%S`
 typeset -i nfiles
+run_ok=`b2fstate_OK`
+[ $run_ok == 'yes' ] && {
 
-( ls -l b2mn.exe.dir/tracing/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l tracing/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
-ncfiles=`ls -l b2mn.exe.dir/tracing/* | grep -v 'total ' | grep -v ' 0 ' | awk '{printf "%s ",$NF,"\n"}'`
 echo "tracing : found" $nfiles "files"
-[ $nfiles -gt 0 ] && for i in $ncfiles; do {
-	mv $i tracing 2> /dev/null || echo > /dev/null
-    }; done
+[ $nfiles -gt 0 ] && {
+  [ -d ../tracing ] || mkdir ../tracing
+  mv tracing/* ../tracing 2> /dev/null || echo > /dev/null
+}
 rm $NAME
 
-( ls -l b2mn.exe.dir/batch_av/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l batch_av/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "batch_av : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/batch_av/* batch_av 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && {
+  [ -d ../batch_av ] || mkdir ../batch_av
+  mv batch_av/* ../batch_av 2> /dev/null || echo > /dev/null
+}
 rm $NAME
 
-( ls -l b2mn.exe.dir/run_av/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l run_av/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "run_av : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/run_av/* batch_av 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && {
+  [ -d ../run_av ] || mkdir ../run_av
+  mv run_av/* ../run_av 2> /dev/null || echo > /dev/null
+}
 rm $NAME
 
-( ls -l b2mn.exe.dir/d?? | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l output/* | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+nfiles=`cat $NAME`
+echo "output : found" $nfiles "files"
+[ $nfiles -gt 0 ] && {
+  [ -d ../output ] || mkdir ../output
+  mv output/* ../output 2> /dev/null || echo > /dev/null
+}
+rm $NAME
+
+( ls -l d?? | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "d?? : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/d?? . 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && mv d?? ../ 2> /dev/null || echo > /dev/null
 rm $NAME
 
-( ls -l b2mn.exe.dir/ds?? | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l ds?? | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "ds?? : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/ds?? . 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && mv ds?? ../ 2> /dev/null || echo > /dev/null
 rm $NAME
 
-( ls -l b2mn.exe.dir/ds??? | grep -v 'total ' | grep -v ' 0 ' | grep -vwc -l > $NAME ) 2> /dev/null
+( ls -l ds??? | grep -v 'total ' | grep -v ' 0 ' | grep -vwc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "ds??? : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/ds??? . 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && mv ds??? ../ 2> /dev/null || echo > /dev/null
 rm $NAME
 
-( ls -l b2mn.exe.dir/b2.*.parameters | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
+( ls -l b2.*.parameters | grep -v 'total ' | grep -v ' 0 ' | wc -l > $NAME ) 2> /dev/null
 nfiles=`cat $NAME`
 echo "b2.*.parameters : found" $nfiles "files"
-[ $nfiles -gt 0 ] && mv b2mn.exe.dir/b2.*.parameters . 2> /dev/null || echo > /dev/null
+[ $nfiles -gt 0 ] && mv b2.*.parameters ../ 2> /dev/null || echo > /dev/null
 rm $NAME
+
+} || {
+
+echo "Run apparently failed: Optional files not moved"
+
+}
